version: '3.8'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: investimentos
      MYSQL_USER: user
      MYSQL_PASSWORD: senha123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    depends_on:
      - db
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: mysql://root:root@db:3306/investimentos

#  frontend:
#    build:
#      context: ./frontend
#    ports:
#      - "3000:3000"
#    volumes:
#      - ./frontend:/app
#      - /app/node_modules
#    environment:
#      - NEXT_PUBLIC_API_URL=http://localhost:3001
#    depends_on:
#      - backend

volumes:
  db_data:
